# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Technically Thinking
<<<<<<< HEAD
email: zacattack@TechnicallyThinking.com
description: >- # this means to ignore newlines until "baseurl:"
  I am Zac Mitton, a web developer living in the San Francisco Bay area.
  This blog does not necessarily reflect the thoughts or opinions that
  people actually know about me in real life. They would probably think I was weird.
  I am. The point of this blog is express some weird ideas in hopes that other
  weird people (like you?) come across them and we can connect.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zacsTwitter
github_username: zmitton

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
=======
email: zacattack@zacmitton.com
description: >- # this means to ignore newlines until "baseurl:"
  I’m Zac Mitton. This is my blog.
baseurl: "/Technically-Thinking/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github:
  owner_url: https://github.com/zmitton
  owner_name: Zac Mitton
twitter:
  username: voltzroad

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  # Un-comment following lines if you'd like line numbers in code syntax
  # syntax_highlighter_opts:
  #   line_numbers: true
  #   start_line: 1
# leave theme blank for cayman-blog theme to work
theme:
>>>>>>> 2cb9717e925b2b1546da61e287644c2fcc79948d
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
